# ================================
# Hydra Configuration
# ================================
hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/outputs_2d_0703_v4_2input   # Output directory for logs and checkpoints

# ================================
# General Settings
# ================================
general:
  seed: 42                            # Random seed for reproducibility

# ================================
# Dataset Settings
# ================================
dataset:
  data_path: ./training_data/patch_training_data/training_data_patch_2d_0703_v4  # Path to dataset folder
  mult_input: 2                      # Number of input time steps
  mult_output: 7                     # Number of output time steps
  noise:
    enable: False                    # Enable noise augmentation
    mul_noise_level: 0.5             # Multiplicative noise strength
    add_noise_level: 0.01            # Additive noise strength
  pressure:
    std: 0.065                       # Pressure normalization standard deviation

# ================================
# DataLoader Settings
# ================================
dataloader:
  train_ratio: 0.9                   # Ratio of dataset used for training
  train_batch_size: 16              # Batch size for training
  val_batch_size: 2                 # Batch size for validation
  num_workers: 8                    # Number of workers for DataLoader

# ================================
# Training Settings
# ================================
training:
  optimizer:
    betas: [0.9, 0.999]             # Adam optimizer beta parameters
  lr_schedule:
    start_lr: 0.001                 # Initial learning rate
    eta_min: 1e-5                   # Minimum learning rate for cosine scheduler
  max_epochs: 30                    # Total training epochs
  save:
    interval: 10                    # Save checkpoint every N epochs
    path: ./savepoints              # Directory to store checkpoints

# ================================
# Model Architecture (FNO)
# ================================
model:
  fno:
    in_channels: 4                 # Input features: e.g., pressure, density, sound speed
    out_channels: 7                # Output features = mult_output
    dimension: 2                   # Spatial dimensionality (2D or 3D)
    latent_channels: 32            # Number of latent channels in FNO layers
    num_fno_layers: 8              # Number of FNO layers (blocks)
    num_fno_modes: 32              # Fourier modes kept in spectral domain
    padding: 4                     # Spatial padding size
    decoder_layers: 1              # Number of decoder (fully connected) layers
    decoder_layer_size: 128        # Width of each decoder layer

